/*
 * BombBomb
 * We make it easy to build relationships using simple videos.
 *
 * OpenAPI spec version: 2.0.831
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * The PromptOverview class
 */
@ApiModel(description = "The PromptOverview class")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-07-30T21:11:01.919Z")
public class PromptOverview {
  @SerializedName("startDate")
  private String startDate = null;

  @SerializedName("endDate")
  private String endDate = null;

  @SerializedName("userBatchListsIdHelper")
  private String userBatchListsIdHelper = null;

  @SerializedName("promptIdHelper")
  private String promptIdHelper = null;

  public PromptOverview startDate(String startDate) {
    this.startDate = startDate;
    return this;
  }

   /**
   * The startDate property
   * @return startDate
  **/
  @ApiModelProperty(value = "The startDate property")
  public String getStartDate() {
    return startDate;
  }

  public void setStartDate(String startDate) {
    this.startDate = startDate;
  }

  public PromptOverview endDate(String endDate) {
    this.endDate = endDate;
    return this;
  }

   /**
   * The endDate property
   * @return endDate
  **/
  @ApiModelProperty(value = "The endDate property")
  public String getEndDate() {
    return endDate;
  }

  public void setEndDate(String endDate) {
    this.endDate = endDate;
  }

  public PromptOverview userBatchListsIdHelper(String userBatchListsIdHelper) {
    this.userBatchListsIdHelper = userBatchListsIdHelper;
    return this;
  }

   /**
   * The userBatchListsIdHelper property
   * @return userBatchListsIdHelper
  **/
  @ApiModelProperty(value = "The userBatchListsIdHelper property")
  public String getUserBatchListsIdHelper() {
    return userBatchListsIdHelper;
  }

  public void setUserBatchListsIdHelper(String userBatchListsIdHelper) {
    this.userBatchListsIdHelper = userBatchListsIdHelper;
  }

  public PromptOverview promptIdHelper(String promptIdHelper) {
    this.promptIdHelper = promptIdHelper;
    return this;
  }

   /**
   * The promptIdHelper property
   * @return promptIdHelper
  **/
  @ApiModelProperty(value = "The promptIdHelper property")
  public String getPromptIdHelper() {
    return promptIdHelper;
  }

  public void setPromptIdHelper(String promptIdHelper) {
    this.promptIdHelper = promptIdHelper;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PromptOverview promptOverview = (PromptOverview) o;
    return Objects.equals(this.startDate, promptOverview.startDate) &&
        Objects.equals(this.endDate, promptOverview.endDate) &&
        Objects.equals(this.userBatchListsIdHelper, promptOverview.userBatchListsIdHelper) &&
        Objects.equals(this.promptIdHelper, promptOverview.promptIdHelper);
  }

  @Override
  public int hashCode() {
    return Objects.hash(startDate, endDate, userBatchListsIdHelper, promptIdHelper);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PromptOverview {\n");
    
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    userBatchListsIdHelper: ").append(toIndentedString(userBatchListsIdHelper)).append("\n");
    sb.append("    promptIdHelper: ").append(toIndentedString(promptIdHelper)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

