/*
 * BombBomb
 * We make it easy to build relationships using simple videos.
 *
 * OpenAPI spec version: 2.0.831
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * The TeamPublicRepresentation class
 */
@ApiModel(description = "The TeamPublicRepresentation class")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-07-30T21:11:01.919Z")
public class TeamPublicRepresentation {
  @SerializedName("id")
  private String id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("createdDate")
  private String createdDate = null;

  public TeamPublicRepresentation id(String id) {
    this.id = id;
    return this;
  }

   /**
   * The id of the team
   * @return id
  **/
  @ApiModelProperty(value = "The id of the team")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public TeamPublicRepresentation name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The name of the team
   * @return name
  **/
  @ApiModelProperty(value = "The name of the team")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public TeamPublicRepresentation createdDate(String createdDate) {
    this.createdDate = createdDate;
    return this;
  }

   /**
   * The date the team was created
   * @return createdDate
  **/
  @ApiModelProperty(value = "The date the team was created")
  public String getCreatedDate() {
    return createdDate;
  }

  public void setCreatedDate(String createdDate) {
    this.createdDate = createdDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TeamPublicRepresentation teamPublicRepresentation = (TeamPublicRepresentation) o;
    return Objects.equals(this.id, teamPublicRepresentation.id) &&
        Objects.equals(this.name, teamPublicRepresentation.name) &&
        Objects.equals(this.createdDate, teamPublicRepresentation.createdDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, createdDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TeamPublicRepresentation {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

