/**
 * BombBomb
 * We make it easy to build relationships using simple videos.
 *
 * OpenAPI spec version: 2.0.22196
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AutomationsApi
 */
public class AutomationsApiTest {

    private final AutomationsApi api = new AutomationsApi();

    
    /**
     * Get Automation Email Stats
     *
     * Get Automation Email Stats
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getDripDropStatsTest() throws ApiException {
        String dripId = null;
        String dripDropId = null;
        // api.getDripDropStats(dripId, dripDropId);

        // TODO: test validations
    }
    
    /**
     * Get Automation Stats
     *
     * Get Automation Stats
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getDripStatsTest() throws ApiException {
        String id = null;
        // api.getDripStats(id);

        // TODO: test validations
    }
    
}
