/**
 * BombBomb
 * We make it easy to build relationships using simple videos.
 *
 * OpenAPI spec version: 2.0.22196
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Curriculum;
import io.swagger.client.model.CurriculumWithProgress;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CurriculumApi
 */
public class CurriculumApiTest {

    private final CurriculumApi api = new CurriculumApi();

    
    /**
     * Get Curricula
     *
     * Get Curricula, optionally with progress included.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCurriculaTest() throws ApiException {
        Boolean includeProgress = null;
        // List<Curriculum> response = api.getCurricula(includeProgress);

        // TODO: test validations
    }
    
    /**
     * Get Detailed For User
     *
     * Get all curricula for user including progress for each curriculum.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUserCurriculumWithProgressTest() throws ApiException {
        // List<CurriculumWithProgress> response = api.getUserCurriculumWithProgress();

        // TODO: test validations
    }
    
}
