/**
 * BombBomb
 * We make it easy to build relationships using simple videos.
 *
 * OpenAPI spec version: 2.0.24005
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ListsApi
 */
public class ListsApiTest {

    private final ListsApi api = new ListsApi();

    
    /**
     * Clear Contacts from List
     *
     * Clears all contacts from a list.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void clearListTest() throws ApiException {
        String listId = null;
        // api.clearList(listId);

        // TODO: test validations
    }
    
    /**
     * Copy All Contacts from a List
     *
     * Copy all contacts from a list.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void copyListContactsTest() throws ApiException {
        String fromListId = null;
        String listId = null;
        // api.copyListContacts(fromListId, listId);

        // TODO: test validations
    }
    
    /**
     * Suppress All Contacts from List
     *
     * Suppresses all contacts in a list.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void suppressAllInListTest() throws ApiException {
        String listId = null;
        // api.suppressAllInList(listId);

        // TODO: test validations
    }
    
}
